### ISSUE TITLE
Kabob Menu - List View Line Item

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ux#16]
JIRA Link: https://patternfly.atlassian.net/browse/RHUAP-260

**Comment by mindreeper2420** [comment]
@joshuawilson @michaelkleinhenz This story is ready for dev.

**Comment by Mgranfie** [comment]
https://redhat.invisionapp.com/share/WB8FNVPYE

**Comment by mindreeper2420** [comment]
Completed.
