### ISSUE TITLE
WIREFRAME: Assign user to Work Item

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ux#40]
[Jira Board Story](https://patternfly.atlassian.net/browse/RHUAP-232)

[Core Issue](https://github.com/almighty/almighty-core/issues/341)

[InVision Mobile Workflow/Wireframe](https://invis.io/838XGP02H)

[InVision Desktop Wireframe](https://redhat.invisionapp.com/share/2D92EG6BH#/199589080_AssignSimple-DT-001)

**Comment by mindreeper2420** [comment]
@joshuawilson @michaelkleinhenz Can either of you (or an assigned dev) take a look at these wireframes and give and comments/ask any questions around the Assign User? This is the first pass, simplified version for just getting a user assigned to the work item and unassigning a user. Thanks!

**Comment by michaelkleinhenz** [comment]
@mindreeper2420 made a comment on the wireframe. Looks consistent for me, only one issue with the position of the assigned user on the detail view.

**Comment by mindreeper2420** [comment]
@michaelkleinhenz I've fixed the link for the workflow. It now shows the correct version with the properly positioned Assign User. The link shoukd have auto updated, but did not. Hope this helps to clear up the positioning question.

**Comment by pranavgore09** [comment]
@mindreeper2420 @Mgranfie - Are those wireframes development-ready ?
If yes, I will update the story.
If not, approximately how much time will it take to reach that state where UI-dev can pick up ?
(asking because in case we decide to pick this up during sprint planning, we will have better idea,)

**Comment by pranavgore09** [comment]
@mindreeper2420 @Mgranfie @michaelkleinhenz , [this comment](https://github.com/almighty/almighty-core/issues/341#issue-181147883) mentions that there will be a `save` button, which should be clicked to set `assignee`. But wireframe has a drop down, by clicking on item, it sets the value.
Can someone please clarify ?

**Comment by michaelkleinhenz** [comment]
@mindreeper2420 @pranavgore09 UX has precedence here. If the UX does save in-place, then we should update the story.

**Comment by pranavgore09** [comment]
thanks @michaelkleinhenz , updating...

**Comment by mindreeper2420** [comment]
Closing as Assign User has been completed.
