### ISSUE TITLE
Investigate Reset Button For Forms

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ux#43]
[Jira Issue](https://patternfly.atlassian.net/browse/RHUAP-438)

**Comment by Mgranfie** [comment]
@mindreeper2420 what is a "reset"button?

**Comment by mindreeper2420** [comment]
@Mgranfie This came through as a request from the development team back when we had a follow-through story - When a user fills out a form (in this case, the entirety of the Details panel), there is no way to clear out everything without selecting each input, highlighting the text, and then deleting the text.

Another instance that currently happens is that there is no way to clear out the inputs of the Quick Add, without closing the Quick Add and opening it up again. The model, as designed, is that you click the 'X' and it will close the inputs and clear the form.

**Comment by Mgranfie** [comment]
@mindreeper2420 If this needed, then we should change the save model to the entire form and not each field and have a Cancel. Has this approach been discussed? This change needs some thought and consideration, as it conflicts with the current Save model.

**Comment by mindreeper2420** [comment]
Closing - refer to patternfly
